### ISSUE TITLE
Question disambiguation

### ISSUE THREAD

**Issue by rmdort** [AskNowQA/EARL#10]
How do you differentiate between

`Where was Barack Obama born` and  `When was Barack Obama born`

In the latter the predicate `born` is `birthDate` and not `birthPlace`. Using answer type (in this case Date) as one of the training feature for ER Predictor may solve this issue?

**Comment by debayan** [comment]
Hi,

Agree with your insight and we will consider making it a part of our solution. 

Thanks.
