### ISSUE TITLE
Code fo GTSP solver and adaptive learning

### ISSUE THREAD

**Issue by vishwajeet93** [AskNowQA/EARL#13]
Hii
Is the code for GTSP solver and adaptive learning open source. Also where can i find code to train my own  ER predictor model?. Please let me know.

**Comment by debayan** [comment]
Unfortunately we do not have code for GTSP we can release. We used some scripts to interface with a 3rd party tool http://www.akira.ruc.dk/~keld/research/GLKH/ to find out GTSP results. Regarding ER model I assign the task to @DeepInEvil  

cc @mohnish-rygbee

**Comment by debayan** [comment]
Have uploaded ER predictor and XG Boost training files 0f3c18552a2c5f59b4a639100a45436a5dd0f573. Also merged a development branch into master. Kindly follow Readme file for changes regarding word embedding similarity matching for relation linking.

**Comment by vishwajeet93** [comment]
Thanks a lot.. :-)
