### ISSUE TITLE
question in TextMatch

### ISSUE THREAD

**Issue by fedesire** [AskNowQA/EARL#14]
Hi,Thank you for your code.But I found when the chunk is predicted as relation,ontologylabeluridict can just help to find candidat uri under http://dbpedia.org/ontology/,so how do we handle the chunks that might link to uri under http://dbpedia.org/property/

**Comment by debayan** [comment]
In the current version of implementation we consider only ontologies, not properties. Property in dbpedia has a lot of noise. Ontologies are clean.
