### ISSUE TITLE
Different results for the same question

### ISSUE THREAD

**Issue by silvanknecht** [AskNowQA/EARL#15]
We use EARL as a relation linker in our QA Pipeline. During tests we noticed that we get different results for the same question. We are using the ranked option of the API.

On 29.4.2019 we asked following question: "Who is the daughter of Bill Clinton married to?"
The result was for:
Daughter: "http://dbpedia.org/ontology/child"
Married: "http://dbpedia.org/ontology/spouse"

Today we asked the same question again and get the result:
Daughter: "http://dbpedia.org/ontology/child"
Married: "http://dbpedia.org/ontology/partner"

What could be the cause of this. Have there been updates to the server or how can we explain this difference?

**Comment by debayan** [comment]
We constantly update the EARL endpoint, as it is the base for our question answering demo asknowdemo.sda.tech. The current live api does not reflect the EARL paper anymore. The results will keep changing, unfortunately.
For constant results you will have to set it up on your own servers.

**Comment by silvanknecht** [comment]
Ok. Thank you for your fast response!
