### ISSUE TITLE
IndexError in TextMatchServer.py

### ISSUE THREAD

**Issue by 111sarah** [AskNowQA/EARL#21]
Hi,
I'm trying to set up this code. But when I run the TextMatchServer.py file, I got "IndexError: list index out of range" error. Can you help me to solve this error?? (Pls refer the attached screenshot)
![code11](https://user-images.githubusercontent.com/66902235/84663146-63781700-af3a-11ea-8f05-18c19902cf7d.png)

**Comment by debayan** [comment]
Hi Sarah,
You have to also specify the port number. Please send me the output including the command you typed. Please check the Readme file to see how to specify the port number.

**Comment by 111sarah** [comment]
I specified the port number. but still gets the same error. (I'm trying to set up with python 3.7 and I added some print statements to test the execution. you can ignore them )
![code](https://user-images.githubusercontent.com/66902235/84677373-42b8bd00-af4c-11ea-8744-221a26973b62.PNG)

**Comment by 111sarah** [comment]
I specified the port number. Now it doesn't give any result and take a long time to execute. Displayed the print statement only.(I'm trying to set up with python 3.7)
![code111](https://user-images.githubusercontent.com/66902235/84679695-3e41d380-af4f-11ea-96dd-775b975e99ca.PNG)

**Comment by 111sarah** [comment]
This error occurred after running the code,
![error2](https://user-images.githubusercontent.com/66902235/84691708-36d7f580-af62-11ea-9a01-43dc2c187f62.PNG)

**Comment by debayan** [comment]
The code does not work with Python 3.7. It only works with Python 2.6. TextMatchServer does not produce any output. It is an API that api.py accesses. Please read the README file properly before running the code.

**Comment by 111sarah** [comment]
What's the effort on working this in python 3.7?

**Comment by debayan** [comment]
If you can find a version of practnlptools (in https://github.com/AskNowQA/EARL/blob/master/scripts/ShallowParser.py) that works in python 3.6, it is possible to port the EARL code.

**Comment by 111sarah** [comment]
practnlptools works mainly for python 2.7 only. It is not compatible with python 3 versions.

**Comment by 111sarah** [comment]
Hi,
I try to set up the code in the Linux environment with python 2.7.
I have followed all the steps mentioned in the readme file. But the code finished executing with an error. I have attached all the screenshots regarding the steps and error. please be kind enough to help me to solve this error.
![run TextMatchServer py on 8888](https://user-images.githubusercontent.com/66902235/85226403-ea266b80-b3f4-11ea-8b89-db96dbbd75fa.PNG)
![run api py on 4999](https://user-images.githubusercontent.com/66902235/85226408-eeeb1f80-b3f4-11ea-950b-d2059372af36.PNG)
![curl commnd](https://user-images.githubusercontent.com/66902235/85226412-f3173d00-b3f4-11ea-91ff-a6c4e203a16f.PNG)
![error after run the curl comnd](https://user-images.githubusercontent.com/66902235/85226415-f4e10080-b3f4-11ea-8860-ef8244b7141a.PNG)

**Comment by YanaPalacheva** [comment]
Hi! I can only suggest reformulating the query to the question form. Like "Who was born in America?".

I tried to set this up on Windows 10 (64bit), but I got stuck since it seems impossible to install pytorch (1.1.0) for python 2.7. How did you do it, if you still remember? 

I also converted all scripts to python 3 with 2to3 tool, but it also got stuck on another problem: it can't read bloom files:
`Joint Linker initializing
'charmap' codec can't decode byte 0x98 in position 5950: character maps to <undefined>`. 
However, I don't think it's a good strategy to run it on python3 anyway because it seems like I will encounter problems related to that again and again.

**Comment by debayan** [comment]
Thank you for using EARL. 

I will make an attempt to port EARL to python3.x this weekend.

**Comment by YanaPalacheva** [comment]
Hi, thank you very much! 
I basically wanted to see how it works, so I tried live API out, but it crashed with 500 Internal Server Error. Maybe you could have a look at that as well if you have time :)

**Comment by debayan** [comment]
The API has been fixed. Try again.

**Comment by debayan** [comment]
Kindly try the code in branch 'python3'. I have attempted to port to python 3.8. If there are no issues, I shall merge the changes to master branch.

**Comment by debayan** [comment]
Merged the branch to master for better visibility.

**Comment by YanaPalacheva** [comment]
Hi! Thank you very much, it works now!
Minor issues (details: Window 10 OS, conda environment for Python 3.8 64 bit): 

- No matching distribution found for torch==1.4.0 (from -r requirements.txt (line 54))
  Solution: conda install pytorch torchvision cudatoolkit=10.2 -c pytorch

- FileNotFoundError: [Errno 2] No such file or directory: 'C:\\var\\log\\asknowlog'
  Temporary solution: created it manually (maybe it's some OS conflict)

**Comment by debayan** [comment]
@YanaPalacheva great to know that it even works on Windows! We focus on supporting on Linux.

**Comment by nimo21** [comment]
Hi @debayan,
I'm trying to set up this code. Do I need to train the ER predictor and the re-ranker models?
