### ISSUE TITLE
Does the work with any KG?

### ISSUE THREAD

**Issue by dinani65** [AskNowQA/EARL#22]
Hi
I appreciate if u can answer my question.
I want to find the entities/relation of a KG which are related to natural questions. Accoutring to the paper, I think its solution will accomplish my goal! 
Does this code work with any KG (e.g. a subset of Freebase)? Does it take a list of questions and a KG and return the correspond entities for each question?

**Comment by debayan** [comment]
Hello,

Unfortunately it only works with dbpedia right now.
