### ISSUE TITLE
I would like to know if the API provided is still working properly

### ISSUE THREAD

**Issue by AllanY999** [AskNowQA/EARL#27]
I tried to use the API provided in the Readme file but it doesn't seem to work and returns 502 bad gateway.

**Comment by izzyrybz** [comment]
Same here, cannot use the API

**Comment by mrchongyl** [comment]
Same! I'm having problem with both of the provided API.

**Comment by debayan** [comment]
Hello folks,

thanks for your interest. The API is up again.
