### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by ghost** [AskNowQA/EARL#5]
When  I try to run the following command

`python api.py 5000`

I get the error shown in the image.
I tried to fix the flask issue but couldn't, is there a quick way?
![screenshot from 2017-12-20 15-59-31](https://user-images.githubusercontent.com/7516846/34213640-1e4c786c-e5a0-11e7-88e1-962777140e9a.png)

**Comment by debayan** [comment]
Hi,

I have added a new file called dependencies.txt and also updated the README file. You need to install all the python modules mentioned there to run api.py.

**Comment by ghost** [comment]
For that Json does not need to be installed, I still have problems installing practNlptools as I get the following:

![screenshot from 2017-12-20 17-13-34](https://user-images.githubusercontent.com/7516846/34216614-208608e2-e5a9-11e7-8f91-29448f218f3f.png)

**Comment by debayan** [comment]
Updated dependencies.txt

**Comment by ghost** [comment]
Ok, I thing another missing dependency is tensorflow not mentioned in .txt

**Comment by ghost** [comment]
After getting over with dependencies issue I get the following
![screenshot from 2017-12-20 17-35-17](https://user-images.githubusercontent.com/7516846/34217595-2933d0f2-e5ac-11e7-8cd5-885a585203b3.png)

**Comment by debayan** [comment]
Keep installing whatever missing modules you find and let me know. I will add them to dependencies.txt. h5py is also a python module. Install it using pip.
