### ISSUE TITLE
Any plan to publish the data and training files

### ISSUE THREAD

**Issue by rmdort** [AskNowQA/EARL#7]
Hi, Love the work you guys are doing. And this is a wonderful piece of code.

I have been playing with the code, and was wondering if you are planning to publish the training files and data, especially ER Prediction, Reranker

An issue i find is ER Prediction is sensitive to text casing. If i type `who is the president of usa`, it classifies usa as a `relation`. Is this is a fixable problem?

Thanks again

**Comment by debayan** [comment]
Release v0.1.2 handles text in case independent fashion now. https://github.com/AskNowQA/EARL/releases/tag/0.1.2
