### ISSUE TITLE
Share ES mapping and ways to import

### ISSUE THREAD

**Issue by rmdort** [AskNowQA/EARL#8]
Hi could you share the elastic search mapping you are using for `dbpredicateindex14` and `dbentityindex9` indexes. 

What import/export script are you using ?

**Comment by munnellg** [comment]
I'd like to add my own request to the one above. More information on how to import the ES dump would be extremely helpful.

**Comment by debayan** [comment]
We just updated the README.md file to reflect this process. Thank you for your interest in the project.

**Comment by munnellg** [comment]
Thanks a million for the quick reply! I've also found that you need to include the following flag for all the elasticdump commands

`--headers='{"Content-Type": "application/json"}'`

Without this I was unable to import the mappings or the data.

**Comment by debayan** [comment]
Works for me without this headers flag, but I added it to the README.md. Thanks.
