### ISSUE TITLE
Any advice on constructing sparql query

### ISSUE THREAD

**Issue by rmdort** [AskNowQA/EARL#9]
Do you have any advice on generating sparql query from the resulting ER respose?

````
{
    "entities": [
        {
            "uris": [
                {
                    "confidence": 0.8497507038000123,
                    "uri": "http://dbpedia.org/resource/Amnesty_International_USA"
                }
            ],
            "surface": [
                28,
                53
            ]
        }
    ],
    "question": "Where is the headquarter of Amnesty International USA",
    "relations": [
        {
            "uris": [
                {
                    "confidence": 0.3996484675519773,
                    "uri": "http://dbpedia.org/ontology/headquarter"
                }
            ],
            "surface": [
                13,
                24
            ]
        }
    ]
}
````

I was looking at `lcquad.json`. Can that training data be used to train a model ?

**Comment by debayan** [comment]
Hello,

Thank you for your interest. You have spotted us pretty early. The project is not fully developed yet. Another colleague at our lab is working on the sparql part and his project is hosted at https://github.com/AskNowQA/query_generation. We are integrating the two projects and in a few weeks you should be able to get the full solution in our repository.
